85 Authentication Process
Natixar/natixar-frontend pull request #90
Opened 2024-05-27 07:43 UTC by Math712

2024-05-30 15:35 UTC, ChrisNatixar requested changes
This change uses NATIXAR_API_KEY, which is not defined anywhere so the authentication header key is not actually added to the http request headers. Suggest you change this to VITE_FUSION_AUTH_CLIENT_KEY for now, and we will correct it properly when the backend is ready.

2024-06-03 11:24 UTC, Math712 commented
The name proposal `VITE_FUSION_AUTH_CLIENT_KEY` is impossible because this var name already exist

2024-06-03 18:18 UTC, ChrisNatixar approved these changes
The NATIXAR_API_KEY will need to be defined for this PR to take effect.

2024-06-03 18:23 UTC, ChrisNatixar approved these changes

2024-06-03 18:25 UTC, merged